// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSEqm9D14fYjaCPRQOcSEwhFXN6stnkE',
    appId: '1:1017491029322:android:90c6214f9e2506aaa155b3',
    messagingSenderId: '1017491029322',
    projectId: 'autocare-fa103',
    storageBucket: 'autocare-fa103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbH_wPzYgaYkdnUset00eqERd1OEfClag',
    appId: '1:1017491029322:ios:2112a9de9bf2827ca155b3',
    messagingSenderId: '1017491029322',
    projectId: 'autocare-fa103',
    storageBucket: 'autocare-fa103.appspot.com',
    androidClientId: '1017491029322-iksa1t95k7r2rv7lg9vo9r2dcpsq4op2.apps.googleusercontent.com',
    iosClientId: '1017491029322-9l27njb8s11vaheobos8ocl3lqs3nd6q.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
